Deployable architecture
terraform-ibm-modules/terraform-ibm-mq-cloud pull request #49
Opened 2024-08-29 13:46 UTC by shemau

### Description

Implement standard solution in preparation for deployable architecture.

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Add standard solution

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-08-29 13:47 UTC, shemau commented
/run pipeline

2024-08-30 16:48 UTC, shemau commented
/run pipeline

2024-09-09 08:55 UTC, shemau commented
/run pipeline

2024-09-09 15:46 UTC, shemau commented
/run pipeline

2024-09-09 17:20 UTC, shemau commented
THIS IS AN INCUBATING MODULE and this a BREAKING change. Inputs and outputs to modules and sub modules change. UPGRADE TESTING will not work and are intentionally SKIPPED.

2024-09-10 09:08 UTC, shemau commented
/run pipeline

2024-09-11 13:49 UTC, shemau commented
/run pipeline

2024-09-12 12:21 UTC, ocofaigh requested changes
Left some comments. Also your missing the update needed in `.releaserc` to auto trigger the catalog pipeline

2024-09-12 12:21 UTC, ocofaigh commented on tests/pr_test.go
> +
I suggest changing the upgrade test (`TestRunUpgradeExample`) to point to the DA code

2024-09-12 12:21 UTC, ocofaigh commented on solutions/standard/outputs.tf
> +# REVIEWER CHECK!!! Should all queue manager fields be output since this is a Deployable Architecture
No harm in outputting as many things as possible in the DA

2024-09-12 12:21 UTC, ocofaigh commented on solutions/standard/catalogValidationValues.json.template
> +  "existing_mq_capacity_crn": $HPCS_US_SOUTH_CRN,
Ah I'm going to have to add support to the catalog pipeline to pull the MQ capacity CRN here - I created an internal issue

2024-09-12 12:21 UTC, ocofaigh commented on solutions/standard/catalogValidationValues.json.template
> +  "deployment_name": "da-mq-instance",
Does this have to be unique? If so, maybe go with `$PREFIX` as the value?

2024-09-12 12:21 UTC, ocofaigh commented on ibm_catalog.json
> +                  "profile_name": "CIS IBM Cloud Foundations Benchmark",
Is there even any SCC rules in any profiles for anything the DA deploys? If there is not, there is no point in adding anything for compliance here (can be set to `"compliance": {}`).

Also this profile is deprecated. The latest one is called `CIS IBM Cloud Foundations Benchmark v1.1.0` (yes with the version in the name) and the version is `1.1.0`

2024-09-16 14:45 UTC, shemau commented
/run pipeline

2024-09-20 08:37 UTC, shemau commented
/run pipeline

2024-09-20 09:50 UTC, ocofaigh commented on .catalog-onboard-pipeline.yaml
> +  - name: deploy-arch-ibm-mqcloud
this needs to match the value in ibm_catalog.json which is `deploy-arch-ibm-mq-cloud`. This is the value we set up in catalog so needs to match here

2024-09-20 10:01 UTC, ocofaigh approved these changes

2024-09-20 10:19 UTC, merged

2024-09-20 10:19 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 0.0.2 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-mq-cloud/releases/tag/v0.0.2)
- `v0.0.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: